#print('Olá! Seja bem vindo ao programa do Marco!')
import time
#time.sleep (2)
#print ('Gostaria de fazer algumas perguntas, vamos começar?')
#time.sleep (2)
#nome = input ("qual o seu nome?")
#time.sleep (2)
#print("Bem vindo",nome,'!')
#time.sleep(2)
idade = input ('Quantos anos você tem?')
print ("Você tem",idade, "anos certo?")
respostaidade = input ()
if respostaidade == ('nao') : idade = input ('Vamos tentar de novo? Quantos anos você tem?')
print ("Você tem",idade, "anos certo?")
if respostaidade == ('nao') : idade = input ('Vamos tentar de novo? Quantos anos você tem?')
if respostaidade == ('sim') : (print ('maravilha'))
print ('Muito obrigado por conversar comigo!')

